### ISSUE TITLE
[Bug] Colour scheme Style Settings options overlap

### ISSUE THREAD

**Issue by damiankorcz** [7368697661/Ultra-Lobster#1]
Hey @7368697661,
I just noticed that you are using the same `value` names for the Light and the Dark theme colour schemes in Style Settings. This causes the Light theme to change the Dark theme's colour scheme and vice versa. You can resolve that by having different `value` names while keeping the same `label` names if you want to have them the same. I personally handle these cases in my theme by adding `-lt` for Light theme or `-dt` for Dark theme as a suffix to the `value` names. Basically, they need to be different so that they don't trigger the other theme.

**Comment by damiankorcz** [comment]
In case you aren't sure what I mean, here is a modified version of your theme that fixes the problem by adding the `-lt` and `-dt` suffixes where necessary.
[theme.zip](https://github.com/7368697661/Ultra-Lobster/files/9844689/theme.zip)

**Comment by AnubisNekhet** [comment]
I don't think colorscheme values will overlap each other since they're defined in their own theme (light or dark in this case) since theres a `.theme-dark` and `.theme-light` selector on top of the colorscheme values.
This will ensure that the proper variant of the colorscheme is being used (unless you add a `.theme-light` or .`theme-dark` value to the body element) separately.

**Comment by AnubisNekhet** [comment]
Another thing to keep in mind is that using more variables may take up more memory space than usual, which isn't really optimal for an electron application.

**Comment by tingmelvin** [comment]
> I don't think colorscheme values will overlap each other since they're defined in their own theme (light or dark in this case) since theres a `.theme-dark` and `.theme-light` selector on top of the colorscheme values. This will ensure that the proper variant of the colorscheme is being used (unless you add a `.theme-light` or .`theme-dark` value to the body element) separately.

This is incorrect. As the author used `class-select` on Style Settings, choosing another theme with either the Light theme or Dark theme dropdowns on the theme itself would cause it to override because of the same names. Having similar classes only means that even if you opt to change _only_ the dark mode, it will apply to light mode.

You can test this out yourself by downloading the theme and playing around with Style Settings. It would be immediately obvious.

**Comment by damiankorcz** [comment]
@AnubisNekhet, that's a good principal to have for sure but personally I've noticed minimal (if any) major memory use despite having a lot of variables set through Style Settings. I wouldn't worry about it too much unless you notice issues on your end.

**Comment by AnubisNekhet** [comment]
Ah, I see what I did wrong 😅
I didn't notice there were separate toggles for light and dark themes.
I assumed the theme made you pick a colorscheme for both variants and based my line of reasoning off of that.
I definitely agree then, the theme should be rewritten as you said.

**Comment by 7368697661** [comment]
Omg thank you so much, everyone 🥰 Sorry, for some reason Style Settings is simply not clicking in my head, back to the research material 😅 

@damiankorcz thank you so much for that fix! It should be brought in with the new theme file (I gave you credit, too, if that's ok!)

Also, thank you all for the comments, they are super helpful!

**Comment by damiankorcz** [comment]
Swing by the `theme-dev` channel on Obsidian Discord if you need help in the future😉
Also, no need for credit but I appreciate it!
