### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by ct324** [7368697661/Ultra-Lobster#6]
I can't seem to change the fonts of the titles, interface and monospace individually. The interface font seems to control the entire app and the other options for monospace and titles don't do anything.

**Comment by 7368697661** [comment]
Hi! I am actually in the middle of re-doing the fonts so I can let people choose stuff via Style Settings! I should have a new version soon, so bear with me and I'll let you know when it's done! I would love to know if it fixes the issue you are having, because I totally noticed _something_ was not working right

**Comment by ct324** [comment]
Awesome! Thank you so much. I absolutely love this theme can't wait to see what you can do with it :)

**Comment by 7368697661** [comment]
Oh my goodness I am so glad you are enjoying it!!
(psst I uploaded a sneaky update, want to let me know if it helps at all? 🥰)
